/*

 THESIMPLESTBACKGROUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\Users\nkyb1\Downloads\gbtd22\simple_backgrounds.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define backgrounddemoWidth 40
#define backgrounddemoHeight 18
#define backgrounddemoBank 0

extern unsigned char backgrounddemo[];

/* End of THESIMPLESTBACKGROUND.H */
